### ISSUE TITLE
Render time

### ISSUE THREAD

**Issue by sjtuytc** [rohitgirdhar/CATER#14]
Hi, I'm using blender 2.83 because using 2.79b would raise no GLU.so error. I have opened CUDA. However, it seems the rendering process is extremely slow. (More than one hour for one video) Is it normal?
<img width="724" alt="截屏2020-07-24 上午12 06 48" src="https://user-images.githubusercontent.com/31123348/88310662-84563800-cd42-11ea-9dae-2cf648c93a01.png">

**Comment by rohitgirdhar** [comment]
Unfortunately I don't have the runtime numbers anymore, though depending on the GPU 1 hour might be possible. One way to make sure it's running at full capacity is to see if your GPU utilization is high; if so then it's unlikely you can make it much faster anyway
