### ISSUE TITLE
How to get the GT masks of objects?

### ISSUE THREAD

**Issue by sjtuytc** [rohitgirdhar/CATER#15]
Hi, I want to run some segmentation codes (e.g. Mask RCNN) so I need the gt masks of objects in the scene. CLEVRER has provided them but CATER does not. I want to know do you plan to release the masks of objects? If not, how can we get them?

**Comment by rohitgirdhar** [comment]
In the pre-generated dataset, unfortunately there's no easy way to get segmentation maps (more discussion in https://github.com/rohitgirdhar/CATER/issues/7). It should be possible to generate it when generating the data though, for eg, by rendering additional videos with 1 object at a time without lighting in a uniform color, and thresholding (similar to how [CLEVR checks for visibility](https://github.com/facebookresearch/clevr-dataset-gen/blob/f0ce2c81750bfae09b5bf94d009f42e055f2cb3a/image_generation/render_images.py#L475)).
