### ISSUE TITLE
Names of the classes in gt files.

### ISSUE THREAD

**Issue by sjtuytc** [rohitgirdhar/CATER#17]
Hi, I'd like to get the names of the classes in gt files in task 1 and task2, which should be 14 classes and 301 classes in total. Can you help me?

**Comment by rohitgirdhar** [comment]
You can use instructions in https://github.com/rohitgirdhar/CATER/issues/8 for Task 2. Task 1 you can simply get [here](https://github.com/rohitgirdhar/CATER/blob/b45bf796fbe5fdbabea38698b003f64a0ac43bff/generate/gen_train_test.py#L27).
