### ISSUE TITLE
Error due to changes in video folder files in official Pytorch directory

### ISSUE THREAD

**Issue by abhaygargab** [rohitgirdhar/CATER#21]
Hello Rohit, I ran into yet another error which i could not solve after repeatedly trying everything i could in the last 4 days.

In file included from /home/u1698461/Downloads/CATER-master/pytorch_once_again/pytorch/caffe2/video/customized_video_io.cc:25:0:
/home/u1698461/Downloads/CATER-master/pytorch_once_again/pytorch/caffe2/video/customized_video_io.h:30:10: fatal error: caffe/proto/caffe.pb.h: No such file or directory
#include "caffe/proto/caffe.pb.h"
^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
caffe2/CMakeFiles/torch_cpu.dir/build.make:6166: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/video/customized_video_io.cc.o' failed
make[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/video/customized_video_io.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/u1698461/Downloads/CATER-master/pytorch_once_again/pytorch/caffe2/video/customized_video_input_op.cc:25:0:
/home/u1698461/Downloads/CATER-master/pytorch_once_again/pytorch/caffe2/video/customized_video_input_op.h:43:10: fatal error: caffe2/utils/thread_pool.h: No such file or directory
#include "caffe2/utils/thread_pool.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
caffe2/CMakeFiles/torch_cpu.dir/build.make:6153: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/video/customized_video_input_op.cc.o' failed
make[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/video/customized_video_input_op.cc.o] Error 1
CMakeFiles/Makefile2:9446: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2

Steps Followed:

1. Used python = 3.6
2. I have cloned the official Pytorch repository and replaced the caffe2/video with caffe2_customized_ops/video
3. Ran "conda install --yes opencv" - for Including video processing operators in while installing caffe2  
4. Changed the USE_FFMPEG = ON and USE_OPENCV = ON in pytorch/CMakeLists.txt
5. Followed installation steps for linux from here - https://github.com/pytorch/pytorch

I think the reason for this error is that the provided caffe2_customized_ops/video is the modified version of older caffe2/video which has since been modified in the official Pytorch repository.

I tried reaching Xiaolong Wang through mail, but didn't get any reply from him.

It would be really helpful if you could spare out just a couple of hours over the weekend in the issue.
The work that i have been doing on the CATER dataset over the last 4 months would be really affected if i cannot run R3D.

Please let me know if you need to know anything.

Thank You

**Comment by rohitgirdhar** [comment]
I’m sorry to hear about the compilation issues you’re facing. Yes those ops are likely only compatible with the older version of caffe2 linked in the repo and need to be compiled with that, and unfortunately I’m unable to keep that code updated to the latest libraries. Apologies for that. However, the data is released in a fairly standard format, and should be compatible with more recent implementations of R3D/NL (eg in pytorch), so you could perhaps try those too using hyperparameters from our config files.

**Comment by abhaygargab** [comment]
Thank You so much for your suggestion.
I found recent implementations of R3D in Pytorch. I should have checked
earlier.
