### ISSUE TITLE
Porting CATER into NVIDIA NeMo

### ISSUE THREAD

**Issue by Kokkini** [rohitgirdhar/CATER#22]
I'm working on making CATER one of the available dataset in NVIDIA [NeMo](https://github.com/NVIDIA/NeMo). To do so, I need to be able to download all data programmatically through static download links. As I noticed, only Scenes and Videos directory have static download links. The Lists directory can only be downloaded manually from box.com. Can you also add static download links for the Lists directory? Thank you.

**Comment by rohitgirdhar** [comment]
Resolved by https://github.com/rohitgirdhar/CATER/commit/703e6004d80f6f1859f9f1bf4cadba44947b4163
