### ISSUE TITLE
Faster Download links in Mainland China!

### ISSUE THREAD

**Issue by ruiyan1995** [rohitgirdhar/CATER#24]
@rohitgirdhar 
We have uploaded the dataset to Baidu Cloud and now share it with people from Mainland China as follows. 
[Baidu Cloud link](https://pan.baidu.com/s/1Jd5xM6J9mNdobBR33yfQPA )
code：**d9nk**

**Comment by rohitgirdhar** [comment]
Great thanks! Do you mind if I add this link to the main README (with attribution of course)?

**Comment by ruiyan1995** [comment]
> Great thanks! Do you mind if I add this link to the main README (with attribution of course)?

Sure!
