### ISSUE TITLE
corrupted videos in pre-generated data

### ISSUE THREAD

**Issue by vmichals** [rohitgirdhar/CATER#27]
There are several corrupted video files in the downloadable zip datasets, e.g. 'videos/CATER_new_004798.avi' in the 
max2action task (see [screenshot](https://user-images.githubusercontent.com/1757177/119590423-45f73280-bdc4-11eb-8109-aec022cb6c71.png)). We downloaded the archive multiple times and the same files are corrupted.
How should we handle this?

Code to see the issue:
```
wget https://cmu.box.com/shared/static/jgbch9enrcfvxtwkrqsdbitwvuwnopl0.zip
# extract one corrupted video
unzip videos.zip videos/CATER_new_004798.avi
# open in a media player:
# vlc videos/CATER_new_004798.avi
# mplayer videos/CATER_new_004798.avi
```

**Comment by rohitgirdhar** [comment]
Hi, thanks for your interest.
Yes unfortunately there are some corrupted videos as except for some basic automated checks [here](https://github.com/rohitgirdhar/CATER/blob/13a19643f1a2fb24e931df25abd74353e4f2fdcb/generate/gen_train_test.py#L209), we were unable to manually verify that all the videos were rendered/stored correctly. You can choose to ignore those videos, I believe our baseline code either ignores or returns a dummy/mean-image like output for any video it can not decode.

**Comment by vmichals** [comment]
Thanks for the quick reply! We'll simply skip them for now!
