### ISSUE TITLE
Weights of Non-local Networks, Fine-tuned on CATER

### ISSUE THREAD

**Issue by noureldien** [rohitgirdhar/CATER#5]
Hi Rohit,

Awesome work. Thanks for contributing to the society, and for sharing the code with the community.
Can you share the model weights on non-local-network that you fined-tuned on CATER?

Thanks,
Nour

**Comment by rohitgirdhar** [comment]
Hi Nour, thanks for your interest and the kind words. I've added a link to the model in the [README](https://github.com/rohitgirdhar/CATER/blob/master/baselines/README.md#launch-non-local-training-pipeline).

**Comment by noureldien** [comment]
Rohit,  Thanks for finding the time to upload it.
All the best.
