### ISSUE TITLE
Labels corresponding to 301 classes of Task 2

### ISSUE THREAD

**Issue by abhaygargab** [rohitgirdhar/CATER#8]
Hello Authors,
Thanks for such a great work.
I could not find the labels corresponding to 301 classes of Task 2.
Can you please point out that list?

Thank You

**Comment by rohitgirdhar** [comment]
Thanks for your interest! Unfortunately we didn't store it in the released data folder, but you can recreate that file using the [actions_order_dataset({}, n=2, unique=True)](https://github.com/rohitgirdhar/CATER/blob/b45bf796fbe5fdbabea38698b003f64a0ac43bff/generate/gen_train_test.py#L169-L200) function.

**Comment by abhaygargab** [comment]
Thank You for your quick reply, however i am getting this error while i used the above command:

Action orders classes 301
Computing action order labels: 0it [00:00, ?it/s]
Traceback (most recent call last):

  File "<ipython-input-13-04859bea1a42>", line 1, in <module>
    x =  actions_order_dataset({}, n=2, unique=True)

  File "<ipython-input-12-6345dd3fc04a>", line 29, in actions_order_dataset
    num_labels_active /= len(data)

ZeroDivisionError: division by zero

**Comment by abhaygargab** [comment]
I could solve the error and get the classes.
Thank You so much for the help.

**Comment by robinzixuan** [comment]
if the generation of the corresponding label is based on some videos? If yes, what video should be?

**Comment by maskaravivek** [comment]
I just generated the labels corresponding to the 301 classes using the function mentioned by Rohit.

Here's the gist file with the class names if anyone needs it. 

https://gist.github.com/maskaravivek/eacd5fc4adae51fdb5c2ea26d3c9c15d
